# Generated by Django 2.2.5 on 2021-06-05 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('cylinderId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gasName', models.CharField(max_length=200)),
                ('cylinderSize', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('Fill', 'fill'), ('Empty', 'empty')], default='fill', max_length=40)),
                ('Availability', models.CharField(choices=[('Available', 'available'), ('Unavailable', 'unavailable'), ('Issued', 'issued')], default='Available', max_length=40)),
                ('EntryDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue_Date', models.DateTimeField(null=True)),
                ('issue_user', models.CharField(max_length=70, null=True)),
                ('return_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=20)),
                ('status', models.CharField(choices=[('Fill', 'fill'), ('Empty', 'empty'), ('refill', 'Refill')], max_length=10)),
                ('returnDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entry.Cylinder')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=60)),
                ('issueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entry.Cylinder')),
            ],
        ),
    ]
