# Generated by Django 3.1.2 on 2021-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cylinder',
        ),
        migrations.AddField(
            model_name='issue',
            name='cylinder',
            field=models.ManyToManyField(to='Entry.Cylinder'),
        ),
        migrations.RemoveField(
            model_name='return',
            name='cylinder',
        ),
        migrations.AddField(
            model_name='return',
            name='cylinder',
            field=models.ManyToManyField(to='Entry.Cylinder'),
        ),
        migrations.AlterModelTable(
            name='cylinder',
            table='cylinders',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issues',
        ),
        migrations.AlterModelTable(
            name='return',
            table='returns',
        ),
    ]
